### ISSUE TITLE
Использование опресанда & (его отсутсвие в Stylus файлах)

### ISSUE THREAD

**Issue by krashaen** [in19farkt/resume#1]
например:
.article
  margin-top: 10.4%

.article__title
  vertical-align middle
  background linear-gradient(to bottom, #ffffff 45%, #3d6cb0 45%, #3d6cb0 52%, #ffffff 52%)

стоило бы использовать так:
 .article
  margin-top: 10.4%

     &__title
     vertical-align middle
     background linear-gradient(to bottom, #ffffff 45%, #3d6cb0 45%, #3d6cb0 52%, #ffffff 52%)

**Comment by in19farkt** [comment]
Исправил.
