### ISSUE TITLE
Клонирование классов в education и experience

### ISSUE THREAD

**Issue by krashaen** [in19farkt/resume#5]
experience__company === education__profession
может стоило сделать отдельный модуль

**Comment by in19farkt** [comment]
Исправил.

**Comment by krashaen** [comment]
![image](https://cloud.githubusercontent.com/assets/12808495/19259639/ac144afc-8fad-11e6-92c6-205620abeeca.png)
Эта часть должна быть отдельным модулем

**Comment by in19farkt** [comment]
Так ведь это и есть отдельный блок, лежит в папке `frontend/blocks/experience`:
`mixin experience(profession, date, organization)
  .experience
    .experience__marker
    .experience__title
      span.experience__profession #{profession}
      span.experience__date // #{date}
      span.experience__organization #{organization}
      .experience__content
        block`

А использую я его так:
`+article('education', 'education')
  +experience('master degree', 'Feb 2011 - Jun 2014', 'university name')
    p Lorem ipsum dolor sit amet, consectetuer adipiscing...`

**Comment by krashaen** [comment]
извиняюсь, не доглядел...
