### ISSUE TITLE
Просвечивает линия между кругом и текстом

### ISSUE THREAD

**Issue by krashaen** [in19farkt/resume#6]
![image](https://pp.vk.me/c637423/v637423168/13033/cqz6bcn2XyY.jpg)

а также линия теперь не по центру

**Comment by in19farkt** [comment]
![image](https://cloud.githubusercontent.com/assets/12945918/19265706/62598828-8fd0-11e6-8b3e-f7aac2bc42ea.png)
Исправил просвечивание, а линия у меня во всех браузерах по центру, даже если изменять масштаб и размер шрифта html-тега.

**Comment by krashaen** [comment]
![image](https://cloud.githubusercontent.com/assets/12808495/19266737/36471066-8fd5-11e6-8b77-699ad4f79e7f.png)

**Comment by krashaen** [comment]
странно, мы смотрели на нескольких компьютерах, у всех не по центру, может какие то проблемы из за версии ПО...

**Comment by in19farkt** [comment]
Нашел в чем косяк. Это не линия не по центру, а текст. 
![image](https://cloud.githubusercontent.com/assets/12945918/19268263/a2a0ff62-8fdd-11e6-92bf-e09890fbd124.png)
И еще иконка выпадала из контейнера заголовка
![image](https://cloud.githubusercontent.com/assets/12945918/19268289/d7cd0582-8fdd-11e6-8858-b2a256983ab4.png)
Cделал его флексом и выровнял поперечную ось по центру. Можете проверить как у вас выглядит)

**Comment by krashaen** [comment]
Хорошо)
